spring:
  application:
    name: TrackingOrder
  jackson:
    serialization:
      indent-output: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/trackingorder2
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: trackingorder.shop@gmail.com
#    password: abcdefghijklmnop
#
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true



server:
  port: 8111

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true